### ISSUE TITLE
can't run Violist correctly

### ISSUE THREAD

**Issue by louison** [USC-SQL/Violist#1]
Thank you for your reply,
Do I still have to instrument the apk before running Violist on this new version ?
Can I create my own classlist.txt ?

Following your instructions, I'm able to start Violist on my apk with this config : 
```
 parentFolderOfandroid--1=app_debug_example
 parentFolderOfApk=app_debug_example/AppDebug
 apkName=app-debug.apk
 classlist=classlist.txt
 loopUnraveledTime=1
 <android.webkit.WebView: void loadUrl(java.lang.String)>@1
```
But the program stops because of this error : 
Exception in thread "main" java.lang.reflect.InvocationTargetException

thank you for your help !

**Comment by winsonlyu** [comment]
You don't have to instrument the app and you should create your own classlist.txt.
You can make use of the soot-trunk.jar and run the following command: 
java -jar soot-trunk.jar -android-jars path-to-parentFolderOfandroid--1 -src-prec apk -f J -process-dir path-to-XXX.apk -allow-phantom-refs

And you can write a simple program to read the names of all the generated files in sootOutput and write them to classlist.txt

As for the exception, I haven't encountered it before. Let's see if the exception is gone after you update the classlist.txt. It may be due to soot's limitation. If it is the case, you may want to test on another app.

**Comment by louison** [comment]
Ok, seems to work on some apps !

Thank you for your help :)
