### ISSUE TITLE
Other primitive type value?

### ISSUE THREAD

**Issue by paradox5566** [USC-SQL/Violist#3]
Hi, I am looking for the opportunity of extending Violist.
One challenge I found is it did not handle the variable other than the String type. If I want to improve it by considering other primitive data such as int, long, where would you suggest me to start and where should I look at?

**Comment by winsonlyu** [comment]
Hi, thanks for being interested in Violist. I think handling other primitive data types is out of the scope of Violist as its underlying mathematical model was designed to capture string computations. Do you mean to use Violist's model to compute other primitive data types?

**Comment by paradox5566** [comment]
Yes, I am thinking of supporting the case like this:

```java
  void foo(){
    double num1 = 3.5;
    double num2 = num1 + 2.5;
    String str = "456";
    str = str.concat(String.valueOf(num));
    // Expect to see str <- "4566.0"
}
```

The idea I currently had is to modify the class ConstantInt to make it support this kind of simple computation. What other classes should I take care of?

**Comment by winsonlyu** [comment]
It may require substantial changes. Violist currently would not recognize the numeric computations such as +. You can try to modify ir/InterRe.java so that Violist can recognize statements like num2 = num1 + 2.5 and build an IR for it. Then in string/Interpreter.java, you can try to specify the logic about how the IR can be interpreted. 

The String.valueOf functionalities are not supported yet as well. You can also modify InterRe.java and Interpreter.java to handle them.

**Comment by paradox5566** [comment]
Thanks for kindly support.
