### ISSUE TITLE
Error when trying to build new version of Violist

### ISSUE THREAD

**Issue by projectbtle** [USC-SQL/Violist#4]
Hello,

I tried to build Violist, via Eclipse as well as via commandline, but it always fails with errors. 

Eclipse shows a large number of "Missing artifact" errors. Maven (via commandline) terminates with 
"`Failed to execute goal on project NewStringAnalysis: Could not resolve dependencies for project NewStringAnalysis:NewStringAnalysis:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at android:android:jar:13: Failed to read artifact descriptor for android:android:jar:13: Could not transfer artifact android:android:pom:13 from/to soot-snapshot (https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/): Failed to transfer file: https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/android/android/13/android-13.pom. Return code is: 400 , ReasonPhrase:Repository version policy: SNAPSHOT does not allow version: 13.`"

Do I need to configure anything else before attempting to build?

Thanks in advance!

**Comment by paradox5566** [comment]
Hi, I happened to know the solution.
The error is raised because maven cannot find the corresponding android.jar in the following path(Linux):
`/home/<your_user_name>/.m2/repository/android/android/13/android-13.jar`

android.jar is the Android SDK that is required to analyze the program's system library.

There are 2 solutions:

1. Download it from [here](https://github.com/Sable/android-platforms/tree/master/android-13), and rename it to android-13.jar then put it at the given path.

2. Remove the following part from the pom.xml and download the [whole library](https://github.com/Sable/android-platforms) to a directory, for example, at "/home/user/android-platforms". Next, you can replace `String androidJar = configs[0].split("=")[1];` with `String androidJar = "/home/user/android-platforms;` in AndroidMain.java.

> \<dependency>
    \<groupId>android\</groupId>
    \<artifactId>android\</artifactId>
    \<version>13\</version>
\</dependency>

Although you can just download one version of SDK from the directory, it is more flexible to let Soot determine the target version of SDK. 

In addition, I also found similar issue in pom.xml, that could be solved following the first method.

>   \<repository>
         \<id>soot-snapshot\</id>
         \<name>soot snapshots\</name>
         \<url>https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/ \</url>
     \</repository>

**Comment by halfond** [comment]
Thank you both.  Is this something that we could help avoid by modifying the pom or adding these instructions to the readme?  Please let us know so we can help avoid similar confusions in the future.  Thanks!

**Comment by winsonlyu** [comment]
Thank you all. I think it is due to some maven dependencies being out-of-date. I just updated the pom.xml and removed the useless dependencies.

**Comment by projectbtle** [comment]
Thank you all for such prompt responses (and apologies for the delay in mine).

**Testing with files from Oct 20, 2018** 
When incorporating the suggestion by @paradox5566, I no longer get the `Failed to collect dependencies at android:android:jar:13... Repository version policy: SNAPSHOT does not allow version: 13` error. However, a different error is thrown: `Could not resolve dependencies for project NewStringAnalysis:NewStringAnalysis:jar:0.0.1-SNAPSHOT: Could not find artifact grappa:grappa:jar:1.2 in usc.sql (http://atlanta.usc.edu:8081/artifactory/repo)`. 

I tried browsing manually to the atlanta.usc.edu repo and got a 404 error, so perhaps the site is down temporarily. I'll try again later. 

In fact, the previous error regarding the android-13 jar file (`Repository version policy: SNAPSHOT does not allow version: 13`) was also thrown when manually browsing to https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/android/android/13/android-13.pom, so perhaps something has changed on their repo?

**Testing with files from Oct 29, 2018** 
When trying with the latest files, a large number of errors were thrown (please see attached file violist_build_errors.txt). But it might be that I am doing something wrong (I am just running `mvn clean install -U` to build).

[violist_build_errors.txt](https://github.com/USC-SQL/Violist/files/2542828/violist_build_errors.txt)

**Comment by winsonlyu** [comment]
Hi,
You would need to manually add the graphs.jar to the build dependency. I will integrate it to the pom file in the future.

**Comment by projectbtle** [comment]
Thank you, that worked.
