### ISSUE TITLE
soot 3.1.0-SNAPSHOT cannot be resolve

### ISSUE THREAD

**Issue by SeanCoek** [USC-SQL/Violist#8]
Try to compile this project but fail with information below:
Could not transfer metadata ca.mcgill.sable:soot:3.1.0-SNAPSHOT/maven-metadata.xml from/to usc.sql (http://atlanta.usc.edu:8081/artifactory/repo): Connect to atlanta.usc.edu:8081 [atlanta.usc.edu/68.181.96.228] failed: Connection refused (Connection refused)

Is the maven repository down?
How can I build this project into an executable file with "jar" format?

**Comment by winsonlyu** [comment]
Hi,
I just removed the following repository from the pom.xml so that maven can load the soot.jar from the correct repository. Please import the graphs.jar manually to the project path. This jar is located in the root folder.

 <repository>
      <id>usc.sql</id>
      <name>USC Software Quality Lab</name>
      <url>http://atlanta.usc.edu:8081/artifactory/repo</url>
   </repository>

As for building the project into an executable file, you can import it to eclipse or intelliJ and then export the project as a runnable jar.

**Comment by SeanCoek** [comment]
Hi,
I have updated the pom.xml and got this error information: 

> Could not find artifact ca.mcgill.sable:soot:jar:3.1.0-SNAPSHOT in soot-snapshot (https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/)

I check out all version of soot from their repositories and cannot find the "3.1.0-SNAPSHOT" version. Is there any problem if I replace it with another version? Or could you upload the library files you used?

**Comment by winsonlyu** [comment]
Hi,
Thanks for pointing this out. Soot has updated their maven repository. I just updated the pom file to keep up with the soot update.
